// <auto-generated />
namespace MyMovieStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adde_GenreClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adde_GenreClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201910061927368_Adde_GenreClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
